[package]
name = "mjml_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "mjml_nif"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.0"
mrml = {version = "0.3.0", git = "https://github.com/media-io/mrml.git" }
